export const PickUp = {
    name: "PICKUP",
    scale: 1,
    modelCar: {
        group: "modelCar",
        rute: ""
    },
    damageTop: [
        { name: 'P1', group: 'top', rute: '', value: 0 },
        { name: 'P2', group: 'top', rute: '', value: 0 },
        { name: 'P3', group: 'top', rute: '', value: 0 },
        { name: 'P4', group: 'top', rute: '', value: 0 },
        { name: 'P5', group: 'top', rute: '', value: 0 },
        { name: 'P6', group: 'top', rute: '', value: 0 },
        { name: 'P7', group: 'top', rute: '', value: 0 },
        { name: 'P8', group: 'top', rute: '', value: 0 },
        { name: 'P9', group: 'top', rute: '', value: 0 },
        { name: 'P10', group: 'top', rute: '', value: 0 },
        { name: 'P11', group: 'top', rute: '', value: 0 },
        { name: 'P12', group: 'top', rute: '', value: 0 }
    ],
    damageFront: [
        { name: 'P1', group: 'front', rute: '', value: 0 },
        { name: 'P2', group: 'front', rute: '', value: 0 },
        { name: 'P3', group: 'front', rute: '', value: 0 }
    ],
    damageBack: [
        { name: 'P1', group: 'back', rute: '', value: 0 },
        { name: 'P2', group: 'back', rute: '', value: 0 },
        { name: 'P3', group: 'back', rute: '', value: 0 },
        { name: 'P4', group: 'back', rute: '', value: 0 },
        { name: 'P5', group: 'back', rute: '', value: 0 },
        { name: 'P6', group: 'back', rute: '', value: 0 }
    ],
    damageLeft: [
        { name: 'P1', group: 'left', rute: '', value: 0 },
        { name: 'P2', group: 'left', rute: '', value: 0 },
        { name: 'P3', group: 'left', rute: '', value: 0 },
        { name: 'P4', group: 'left', rute: '', value: 0 },
        { name: 'P5', group: 'left', rute: '', value: 0 },
        { name: 'P6', group: 'left', rute: '', value: 0 },
        { name: 'P7', group: 'left', rute: '', value: 0 },
        { name: 'P8', group: 'left', rute: '', value: 0 },
        { name: 'P9', group: 'left', rute: '', value: 0 },
        { name: 'P10', group: 'left', rute: '', value: 0 },
        { name: 'P11', group: 'left', rute: '', value: 0 },
        { name: 'P12', group: 'left', rute: '', value: 0 },
        { name: 'P13', group: 'left', rute: '', value: 0 },
        { name: 'P14', group: 'left', rute: '', value: 0 },
        { name: 'P15', group: 'left', rute: '', value: 0 },
        { name: 'P16', group: 'left', rute: '', value: 0 },
        { name: 'P17', group: 'left', rute: '', value: 0 },
        { name: 'P18', group: 'left', rute: '', value: 0 },
        { name: 'P19', group: 'left', rute: '', value: 0 },
        { name: 'P20', group: 'left', rute: '', value: 0 },
        { name: 'P21', group: 'left', rute: '', value: 0 },
        { name: 'P22', group: 'left', rute: '', value: 0 }
    ],
    damageRight:[
        { name: 'P1', group: 'right', rute: '', value: 0 },
        { name: 'P2', group: 'right', rute: '', value: 0 },
        { name: 'P3', group: 'right', rute: '', value: 0 },
        { name: 'P4', group: 'right', rute: '', value: 0 },
        { name: 'P5', group: 'right', rute: '', value: 0 },
        { name: 'P6', group: 'right', rute: '', value: 0 },
        { name: 'P7', group: 'right', rute: '', value: 0 },
        { name: 'P8', group: 'right', rute: '', value: 0 },
        { name: 'P9', group: 'right', rute: '', value: 0 },
        { name: 'P10', group: 'right', rute: '', value: 0 },
        { name: 'P11', group: 'right', rute: '', value: 0 },
        { name: 'P12', group: 'right', rute: '', value: 0 },
        { name: 'P13', group: 'right', rute: '', value: 0 },
        { name: 'P14', group: 'right', rute: '', value: 0 },
        { name: 'P15', group: 'right', rute: '', value: 0 },
        { name: 'P16', group: 'right', rute: '', value: 0 },
        { name: 'P17', group: 'right', rute: '', value: 0 },
        { name: 'P18', group: 'right', rute: '', value: 0 },
        { name: 'P19', group: 'right', rute: '', value: 0 },
        { name: 'P20', group: 'right', rute: '', value: 0 },
        { name: 'P21', group: 'right', rute: '', value: 0 },
        { name: 'P22', group: 'right', rute: '', value: 0 }
    ]
}
