export const Sedan = {
    name: "SEDAN",
    scale: 0.08,
    modelCar: {
        group: "modelCar",
        rute: "./model/Modelo01/sedan.gltf",
    },
    rutes: {
        ruteT: "./model/Modelo01/top.gltf",
        ruteF: "./model/Modelo01/front.gltf",
        ruteB: "./model/Modelo01/back.gltf",
        ruteR: "./model/Modelo01/right.gltf",
        ruteL: "./model/Modelo01/left.gltf",
    },
    damageTop: {
        P1: { name: 'P1', group: 'top', value1: 0, value2: 0, state: "Default" },
        P2: { name: 'P2', group: 'top', value1: 0, value2: 0, state: "Default" },
        P3: { name: 'P3', group: 'top', value1: 0, value2: 0, state: "Default" },
        P4: { name: 'P4', group: 'top', value1: 0, value2: 0, state: "Default" },
        P5: { name: 'P5', group: 'top', value1: 0, value2: 0, state: "Default" },
        P6: { name: 'P6', group: 'top', value1: 0, value2: 0, state: "Default" },
        P7: { name: 'P7', group: 'top', value1: 0, value2: 0, state: "Default" },
        P8: { name: 'P8', group: 'top', value1: 0, value2: 0, state: "Default" },
        P9: { name: 'P9', group: 'top', value1: 0, value2: 0, state: "Default" },
        P10: { name: 'P10', group: 'top', value1: 0, value2: 0, state: "Default" },
        P11: { name: 'P11', group: 'top', value1: 0, value2: 0, state: "Default" },
        P12: { name: 'P12', group: 'top', value1: 0, value2: 0, state: "Default" },
        P13: { name: 'P13', group: 'top', value1: 0, value2: 0, state: "Default" },
        P14: { name: 'P14', group: 'top', value1: 0, value2: 0, state: "Default" },
        P15: { name: 'P15', group: 'top', value1: 0, value2: 0, state: "Default" },
    },
    damageFront: {
        P1: { name: 'P1', group: 'front', value1: 0, value2: 0, state: "Default" },
        P2: { name: 'P2', group: 'front', value1: 0, value2: 0, state: "Default" },
        P3: { name: 'P3', group: 'front', value1: 0, value2: 0, state: "Default" },
    },
    damageBack: {
        P1: { name: 'P1', group: 'back', value1: 0, value2: 0, state: "Default" },
        P2: { name: 'P2', group: 'back', value1: 0, value2: 0, state: "Default" },
        P3: { name: 'P3', group: 'back', value1: 0, value2: 0, state: "Default" },
        P4: { name: 'P4', group: 'back', value1: 0, value2: 0, state: "Default" },
        P5: { name: 'P5', group: 'back', value1: 0, value2: 0, state: "Default" },
    },
    damageLeft: {
        P1: { name: 'P1', group: 'left', value1: 10, value2: 0, state: "Default" },
        P2: { name: 'P2', group: 'left', value1: 20, value2: 0, state: "Default" },
        P3: { name: 'P3', group: 'left', value1: 0, value2: 0, state: "Default" },
        P4: { name: 'P4', group: 'left', value1: 0, value2: 0, state: "Default" },
        P5: { name: 'P5', group: 'left', value1: 0, value2: 0, state: "Default" },
        P6: { name: 'P6', group: 'left', value1: 0, value2: 0, state: "Default" },
        P7: { name: 'P7', group: 'left', value1: 0, value2: 0, state: "Default" },
        P8: { name: 'P8', group: 'left', value1: 0, value2: 0, state: "Default" },
        P9: { name: 'P9', group: 'left', value1: 0, value2: 0, state: "Default" },
        P10: { name: 'P10', group: 'left', value1: 0, value2: 0, state: "Default" },
        P11: { name: 'P11', group: 'left', value1: 0, value2: 0, state: "Default" },
        P12: { name: 'P12', group: 'left', value1: 0, value2: 0, state: "Default" },
        P13: { name: 'P13', group: 'left', value1: 0, value2: 0, state: "Default" },
        P14: { name: 'P14', group: 'left', value1: 0, value2: 0, state: "Default" },
        P15: { name: 'P15', group: 'left', value1: 0, value2: 0, state: "Default" },
        P16: { name: 'P16', group: 'left', value1: 0, value2: 0, state: "Default" },
        P17: { name: 'P17', group: 'left', value1: 0, value2: 0, state: "Default" },
        P18: { name: 'P18', group: 'left', value1: 0, value2: 0, state: "Default" },
        P19: { name: 'P19', group: 'left', value1: 0, value2: 0, state: "Default" },
        P20: { name: 'P20', group: 'left', value1: 0, value2: 0, state: "Default" },
        P21: { name: 'P21', group: 'left', value1: 0, value2: 0, state: "Default" },
        P22: { name: 'P22', group: 'left', value1: 0, value2: 0, state: "Default" },
        P23: { name: 'P23', group: 'left', value1: 0, value2: 0, state: "Default" },
        P24: { name: 'P24', group: 'left', value1: 0, value2: 0, state: "Default" },
    },
    damageRight: {
        P1: { name: 'P1', group: 'right', value1: 0, value2: 0, state: "Default" },
        P2: { name: 'P2', group: 'right', value1: 0, value2: 0, state: "Default" },
        P3: { name: 'P3', group: 'right', value1: 0, value2: 0, state: "Default" },
        P4: { name: 'P4', group: 'right', value1: 0, value2: 0, state: "Default" },
        P5: { name: 'P5', group: 'right', value1: 0, value2: 0, state: "Default" },
        P6: { name: 'P6', group: 'right', value1: 0, value2: 0, state: "Default" },
        P7: { name: 'P7', group: 'right', value1: 0, value2: 0, state: "Default" },
        P8: { name: 'P8', group: 'right', value1: 0, value2: 0, state: "Default" },
        P9: { name: 'P9', group: 'right', value1: 0, value2: 0, state: "Default" },
        P10: { name: 'P10', group: 'right', value1: 0, value2: 0, state: "Default" },
        P11: { name: 'P11', group: 'right', value1: 0, value2: 0, state: "Default" },
        P12: { name: 'P12', group: 'right', value1: 0, value2: 0, state: "Default" },
        P13: { name: 'P13', group: 'right', value1: 0, value2: 0, state: "Default" },
        P14: { name: 'P14', group: 'right', value1: 0, value2: 0, state: "Default" },
        P15: { name: 'P15', group: 'right', value1: 0, value2: 0, state: "Default" },
        P16: { name: 'P16', group: 'right', value1: 0, value2: 0, state: "Default" },
        P17: { name: 'P17', group: 'right', value1: 0, value2: 0, state: "Default" },
        P18: { name: 'P18', group: 'right', value1: 0, value2: 0, state: "Default" },
        P19: { name: 'P19', group: 'right', value1: 0, value2: 0, state: "Default" },
        P20: { name: 'P20', group: 'right', value1: 0, value2: 0, state: "Default" },
        P21: { name: 'P21', group: 'right', value1: 0, value2: 0, state: "Default" },
        P22: { name: 'P22', group: 'right', value1: 0, value2: 0, state: "Default" },
        P23: { name: 'P23', group: 'right', value1: 0, value2: 0, state: "Default" },
        P24: { name: 'P24', group: 'right', value1: 0, value2: 0, state: "Default" },
    },
    light: {
        FL: { name: 'FL', value: 1000, state: "Default" },
        FR: { name: 'FR', value: 20, state: "Default" },
        BL: { name: 'BL', value: 30, state: "Default" },
        BR: { name: 'BR', value: 40, state: "Default" },
    },
    Rin: {
        FL: { name: 'FL', value: 1000, state: "Default" },
        FR: { name: 'FR', value: 20, state: "Default" },
        BL: { name: 'BL', value: 30, state: "Default" },
        BR: { name: 'BR', value: 40, state: "Default" },
    },
    cotizacion: 0
};
