export const Sedan = {
    name: "SEDAN",
    scale: 0.08,
    modelCar: {
        group: "modelCar",
        rute: "./model/Modelo01/sedan.gltf",
    },
    rutes: {
        ruteT: "./model/Modelo01/top.gltf",
        ruteF: "./model/Modelo01/front.gltf",
        ruteB: "./model/Modelo01/back.gltf",
        ruteR: "./model/Modelo01/right.gltf",
        ruteL: "./model/Modelo01/left.gltf",
    },
    damageTop: {
        P1: { name: 'P1', group: 'top', value1: 36, value2: 75, state: "Default" },
        P2: { name: 'P2', group: 'top', value1: 48, value2: 88, state: "Default" },
        P3: { name: 'P3', group: 'top', value1: 77, value2: 38, state: "Default" },
        P4: { name: 'P4', group: 'top', value1: 20, value2: 63, state: "Default" },
        P5: { name: 'P5', group: 'top', value1: 58, value2: 41, state: "Default" },
        P6: { name: 'P6', group: 'top', value1: 33, value2: 27, state: "Default" },
        P7: { name: 'P7', group: 'top', value1: 46, value2: 47, state: "Default" },
        P8: { name: 'P8', group: 'top', value1: 27, value2: 70, state: "Default" },
        P9: { name: 'P9', group: 'top', value1: 16, value2: 59, state: "Default" },
        P10: { name: 'P10', group: 'top', value1: 19, value2: 90, state: "Default" },
        P11: { name: 'P11', group: 'top', value1: 49, value2: 49, state: "Default" },
        P12: { name: 'P12', group: 'top', value1: 75, value2: 26, state: "Default" },
        P13: { name: 'P13', group: 'top', value1: 45, value2: 12, state: "Default" },
        P14: { name: 'P14', group: 'top', value1: 86, value2: 24, state: "Default" },
        P15: { name: 'P15', group: 'top', value1: 63, value2: 72, state: "Default" },
    },
    damageFront: {
        P1: { name: 'P1', group: 'front', value1: 12, value2: 85, state: "Default" },
        P2: { name: 'P2', group: 'front', value1: 24, value2: 73, state: "Default" },
        P3: { name: 'P3', group: 'front', value1: 46, value2: 69, state: "Default" },
    },
    damageBack: {
        P1: { name: 'P1', group: 'back', value1: 52, value2: 50, state: "Default" },
        P2: { name: 'P2', group: 'back', value1: 79, value2: 25, state: "Default" },
        P3: { name: 'P3', group: 'back', value1: 88, value2: 61, state: "Default" },
        P4: { name: 'P4', group: 'back', value1: 37, value2: 28, state: "Default" },
        P5: { name: 'P5', group: 'back', value1: 13, value2: 77, state: "Default" },
    },
    damageLeft: {
        P1: { name: 'P1', group: 'left', value1: 36, value2: 69, state: "Default" },
        P2: { name: 'P2', group: 'left', value1: 85, value2: 39, state: "Default" },
        P3: { name: 'P3', group: 'left', value1: 48, value2: 75, state: "Default" },
        P4: { name: 'P4', group: 'left', value1: 50, value2: 33, state: "Default" },
        P5: { name: 'P5', group: 'left', value1: 31, value2: 68, state: "Default" },
        P6: { name: 'P6', group: 'left', value1: 57, value2: 23, state: "Default" },
        P7: { name: 'P7', group: 'left', value1: 26, value2: 46, state: "Default" },
        P8: { name: 'P8', group: 'left', value1: 62, value2: 82, state: "Default" },
        P9: { name: 'P9', group: 'left', value1: 71, value2: 19, state: "Default" },
        P10: { name: 'P10', group: 'left', value1: 14, value2: 59, state: "Default" },
        P11: { name: 'P11', group: 'left', value1: 45, value2: 47, state: "Default" },
        P12: { name: 'P12', group: 'left', value1: 60, value2: 62, state: "Default" },
        P13: { name: 'P13', group: 'left', value1: 38, value2: 11, state: "Default" },
        P14: { name: 'P14', group: 'left', value1: 72, value2: 14, state: "Default" },
        P15: { name: 'P15', group: 'left', value1: 21, value2: 22, state: "Default" },
        P16: { name: 'P16', group: 'left', value1: 60, value2: 90, state: "Default" },
        P17: { name: 'P17', group: 'left', value1: 33, value2: 84, state: "Default" },
        P18: { name: 'P18', group: 'left', value1: 17, value2: 35, state: "Default" },
        P19: { name: 'P19', group: 'left', value1: 83, value2: 53, state: "Default" },
        P20: { name: 'P20', group: 'left', value1: 25, value2: 58, state: "Default" },
        P21: { name: 'P21', group: 'left', value1: 43, value2: 27, state: "Default" },
        P22: { name: 'P22', group: 'left', value1: 19, value2: 30, state: "Default" },
        P23: { name: 'P23', group: 'left', value1: 74, value2: 16, state: "Default" },
        P24: { name: 'P24', group: 'left', value1: 33, value2: 86, state: "Default" },
    },
    damageRight: {
        P1: { name: 'P1', group: 'right', value1: 67, value2: 48, state: "Default" },
        P2: { name: 'P2', group: 'right', value1: 26, value2: 72, state: "Default" },
        P3: { name: 'P3', group: 'right', value1: 39, value2: 57, state: "Default" },
        P4: { name: 'P4', group: 'right', value1: 21, value2: 11, state: "Default" },
        P5: { name: 'P5', group: 'right', value1: 62, value2: 36, state: "Default" },
        P6: { name: 'P6', group: 'right', value1: 84, value2: 73, state: "Default" },
        P7: { name: 'P7', group: 'right', value1: 92, value2: 26, state: "Default" },
        P8: { name: 'P8', group: 'right', value1: 17, value2: 58, state: "Default" },
        P9: { name: 'P9', group: 'right', value1: 50, value2: 38, state: "Default" },
        P10: { name: 'P10', group: 'right', value1: 82, value2: 45, state: "Default" },
        P11: { name: 'P11', group: 'right', value1: 31, value2: 13, state: "Default" },
        P12: { name: 'P12', group: 'right', value1: 59, value2: 68, state: "Default" },
        P13: { name: 'P13', group: 'right', value1: 44, value2: 55, state: "Default" },
        P14: { name: 'P14', group: 'right', value1: 28, value2: 79, state: "Default" },
        P15: { name: 'P15', group: 'right', value1: 67, value2: 41, state: "Default" },
        P16: { name: 'P16', group: 'right', value1: 52, value2: 21, state: "Default" },
        P17: { name: 'P17', group: 'right', value1: 40, value2: 89, state: "Default" },
        P18: { name: 'P18', group: 'right', value1: 19, value2: 49, state: "Default" },
        P19: { name: 'P19', group: 'right', value1: 73, value2: 67, state: "Default" },
        P20: { name: 'P20', group: 'right', value1: 30, value2: 31, state: "Default" },
        P21: { name: 'P21', group: 'right', value1: 58, value2: 25, state: "Default" },
        P22: { name: 'P22', group: 'right', value1: 46, value2: 82, state: "Default" },
        P23: { name: 'P23', group: 'right', value1: 15, value2: 16, state: "Default" },
        P24: { name: 'P24', group: 'right', value1: 89, value2: 32, state: "Default" },
    },
    light: {
        FL: { name: 'FL', value: 10, state: "Default" },
        FR: { name: 'FR', value: 20, state: "Default" },
        BL: { name: 'BL', value: 30, state: "Default" },
        BR: { name: 'BR', value: 40, state: "Default" },
    },
    Rin: {
        FL: { name: 'FL', value: 10, state: "Default" },
        FR: { name: 'FR', value: 20, state: "Default" },
        BL: { name: 'BL', value: 30, state: "Default" },
        BR: { name: 'BR', value: 40, state: "Default" },
    },
    cotizacion: 0
};
